config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'guests#index'

  resources :guests, only: [:index, :create, :edit]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates   :name, presence: { message: "Ваше имя" }
  validates   :number_of_guests, presence: { message: "Сколько будет гостей?" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guest = Guest.new
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @guest = Guest.new(guest_params)

    if @guest.save
      redirect_to root_path, notice: 'Будем вас ждать!'
    else
      render :index
    end
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :message, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest, remote: true) do |form| %>
  <% if guest.errors.any? %>
        <% guest.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, :image => :warning, sticky: false) %>
    <% end %>
  <% end %>

  <div class="ww-section ww-rsvp-detail text-white" id="rsvp">
    <div class="container" >
      <div class="col text-center">
        <h2 class="h1 ww-title pb-3" >Будем рады вас видеть</h2>
      </div>
      <div class="row ww-rsvp-form">
        <div class="col-md-10">
          <div class="card-body">
            <form action="https://formspree.io/example@email.com" method="POST">
              <div class="row">
                <div class="col md-6 pb-3">
                  <div class="form-group">
                    <div class="field">
                      <%= form.label :name, "Ваше Имя*" %>
                      <%= form.text_field :name, class: "form-control", id: "name-input" %>
                    </div>
                  </div>
                </div>
                <div class="col md-6 pb-3">
                  <div class="form-group">
                    <div class="field">
                      <%= form.label :number_of_guests, "Кол-во Гостей*" %>
                      <%= form.select :number_of_guests, options_for_select([1, 2, 3, 4]), {}, { class: "form-control", id: "guests-input" }%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <div class="field">
                      <%= form.label :message, "Сообщение" %>
                      <%= form.text_area :message, class: "form-control", id: "message-input", rows: "4" %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col text-center">
                  <div class="actions">
                    <%= form.submit "Отправить", class: "btn btn-primary btn-submit", data: { confirm: 'Отправляем?' }  %>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
    <header></header>
    <div class="page-content">
      <div class="div">
<div class="ww-home-page" id="home">
  <div class="ww-wedding-announcement d-flex align-items-center justify-content-start">
    <div class="container ww-announcement-container">
      <p class="ww-couple-name ww-title" data-aos="zoom-in-down" data-aos-delay="300" data-aos-duration="1000">Kim & Angelina</p>
      <div class="save-the-date-img" data-aos="zoom-in-down" data-aos-delay="300" data-aos-duration="1000">
        <%= image_tag "laurel-1.png", class: "img-fluid mt-1" %>
      </div>
      <p class="h2 mt-5 ww-title" data-aos="zoom-in-down" data-aos-delay="300" data-aos-duration="1000" data-aos-offset="10">18<sup></sup>.07.2020</p>
    </div>
  </div>
</div>
<div class="ww-nav-bar sticky-top bg-light">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container"><a href="#"><svg class="heart" viewBox="0 0 32 29.6"><path d="M23.6,0c-3.4,0-6.3,2.7-7.6,5.6C14.7,2.7,11.8,0,8.4,0C3.8,0,0,3.8,0,8.4c0,9.4,9.5,11.9,16,21.2c6.1-9.3,16-12.1,16-21.2C32,3.8,28.2,0,23.6,0z"/>
</svg></a>
      <h1 class="h2"><a class="pl-4 navbar-brand" href="#">Наша свадьба</a></h1>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ww-navbarNav" aria-controls="ww-navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse text-uppercase" id="ww-navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a class="nav-link smooth-scroll" href="#home">Главная</a></li>
          <li class="nav-item"><a class="nav-link smooth-scroll" href="#events">Торжество</a></li>
          <li class="nav-item"><a class="nav-link smooth-scroll" href="#gallery">Галерея</a></li>
          <li class="nav-item"><a class="nav-link smooth-scroll" href="#rsvp">Приглашение</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>
<div class="ww-section bg-light" id="events">
  <div class="container ww-wedding-event">
    <h2 class="h1 text-center pb-3 ww-title" data-aos="zoom-in-down" data-aos-duration="1000">Торжество</h2>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <div class="my-3">
          <div class="h4">Свадебный вечер</div>
          <ul>
            <li><i class="text-muted fas fa-map-marker-alt"></i><span class="pl-2 text-muted">Брестский р-н, д. Тюхиничи 8 ой км трассы М1</span></li>
            <li class="pt-2"><i class="text-muted far fa-calendar-alt"></i><span class="pl-2 text-muted">18 Июля 2020, 14:00</span></li>
          </ul>
          <p>Ресторан «Рынькаускi палац» располагается в загородной усадьбе «Рынькаука» в окрестностях Бреста..
          Все залы имеют профессиональное световое и звуковое оснащение, оборудованы системой кондиционирования воздуха, беспроводным интернетом (бесплатный Wi-Fi). Для комфортного пребывания у нас в инфраструктуру усадьбы входят детская площадка и автомобильная парковка.</p>
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <div class="my-3" alt="Wedding place" data-aos="fade-down-right" data-aos-duration="1000">
          <%= image_tag "wedding-party.jpg", class: "img-fluid" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="ww-section bg-light" id="gallery">
  <div class="ww-photo-gallery">
    <div class="container">
      <h2 class="h1 text-center pb-3 ww-title" data-aos="zoom-in-down" data-aos-duration="1000">Галерея</h2>
      <div class="col-md-12 text-center ww-category-filter mb-4">
        <a class="btn btn-outline-primary ww-filter-button" href="#" data-filter="all">Все</a>
        <a class="btn btn-outline-primary ww-filter-button" href="#" data-filter="we_are">Мы</a>
        <a class="btn btn-outline-primary ww-filter-button" href="#" data-filter="place">Место торжества</a>
      </div>
      <div class="ww-gallery" data-aos="fade-zoom-in" data-aos-easing="ease-in-back" data-aos-delay="300" data-aos-duration="1000" data-aos-offset="0">
        <div class="card-columns">
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-1.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-2.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-3.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-4.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-1.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;place&quot;]">
              <%= image_tag "place-2.jpg", class: "img-fluid" %>
          </div>

          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are2.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are1.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are2.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are.jpg", class: "img-fluid" %>
          </div>
          <div class="card" data-groups="[&quot;all&quot;,&quot;we_are&quot;]">
              <%= image_tag "we_are2.jpg", class: "img-fluid" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'form', guest: @guest %>

<div class="ww-footer bg-light">
  <div class="container text-center py-4">
    <p class="my-0">&copy; Wonderful Wedding. Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
  </div>
</div></div>
</div>
    <footer></footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kim&Angelina</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ким и Ангелина</title>
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/css?family=Dosis:400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js"></script>

    <%= stylesheet_link_tag "aos.css" %>
    <%= stylesheet_link_tag "ekko-lightbox.css" %>
    <%= stylesheet_link_tag "main.css" %>

    <%= favicon_link_tag asset_path('favicon/favicon.png') %>
  </head>

  <body id="top">

    <%= yield %>

    <%= javascript_include_tag "aos.js" %>
    <%= javascript_include_tag "ekko-lightbox.min.js" %>
    <%= javascript_include_tag "main.js" %>
    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], :image => :warning, sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], :time => 3000, :image => :error, sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], :time => 3000, :image => :success, sticky: false) %>
<% end %>